server:
  port: 8080

spring:
  # MySQL 설정 제거, Elasticsearch 설정으로 대체
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
      repositories:
        enabled: true

  security:
    user:
      name: disabled
      password: disabled
    oauth2:
      client:
        registration:
          google:
            client-id: 593436658704-bbim1nlvh72j8k7rbu2751s6ocpu6je1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          naver:
            client-id: JO1wrqzGvkOf4NVT_G73
            client-secret: QsRU1_kIMu
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: 028f332a57b82088dc502e2985fda1ee
            client-secret: SkpkKFPZLnNWDFW2U5lYxPPPHGsFZtJg
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: my-jwt-secret-key-12345678901234567890123456789012
  expiration: 1800000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.data.elasticsearch: DEBUG

dart:
  api:
    key: 6e2ab5d8f2faf7c2100fa0f497ee31d5e6aa902e
    how: 위에 key에다가 아래에서 원하는 키 넣으면 됨
    obj: 4726810cd40e580c803eb6966f1677df83556317
    ljh: 6e2ab5d8f2faf7c2100fa0f497ee31d5e6aa902e
