server:
  port: 8080

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  config:
    # 'optional:' prefix prevents startup failure if a secret is not found.
    import:
      - "optional:aws-secretsmanager:/rds/finalproject"
      - "optional:aws-secretsmanager:/app/finalproject"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
