server:
  port: 8080

spring:
  config:
    import:
      - "aws-secretsmanager:rds/testuser"          # DB 관련 시크릿
      - "aws-secretsmanager:DART/JWT/KAKAO/NAVER/GOOGLE/URL"  # 나머지 API/키 시크릿

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  opensearch:
    uris: ${ELASTICSEARCH_ENDPOINTS:http://192.168.0.77:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:ai-backend-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_SECRET_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

dart:
  api:
    key: ${DART_API_KEY}
    obj: ${DART_API_KEY_OBJ}
    ljh: ${DART_API_KEY_LJH}
    base-url: ${DART_BASE_URL}

frontend:
  url: ${FRONTEND_URL}

security:
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
        kakao:
          client-id: ${KAKAO_CLIENT_ID}
          client-secret: ${KAKAO_CLIENT_SECRET}
