spring:
  config:
    import:
      - "aws-secretsmanager:rds/testuser"
      - "aws-secretsmanager:DART/JWT/KAKAO/NAVER/GOOGLE/URL"

  datasource:
    url: jdbc:mariadb://${host}:${port}/${dbname} # Secrets Manager의 host, port, dbname 키를 사용합니다.
    username: ${username}
    password: ${password}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    elasticsearch:
      cluster-nodes: localhost:9200 # 오픈서치 주소
      username: admin
      password: admin

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ai-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    user:
      name: disabled
      password: disabled
    oauth2: # Secrets Manager의 키 이름과 플레이스홀더를 일치시킵니다.
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [ email, profile ]
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: [ name, email, profile_image ]
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: [ profile_nickname, account_email, profile_image ]
            client-name: Kakao
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

jwt: # Secrets Manager의 키 이름과 플레이스홀더를 일치시킵니다.
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_SECRET_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

dart:
  api:
    # Secrets Manager의 키 이름과 플레이스홀더를 일치시킵니다.
    obj: ${DART_API_KEY_OBJ}
    ljh: ${DART_API_KEY_LJH}
    base-url: https://opendart.fss.or.kr/api

frontend:
  url: ${FRONTEND_URL}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.data.opensearch: DEBUG
    # org.springframework.data.elasticsearch: DEBUG
