name: CI/CD - Build and Push backend Docker Image

on:
  push:
    branches:
      - feature/infra

jobs:
  # build-and-push 라는 이름의 작업
  build-and-push:
    # 이 작업이 실행될 가상 환경
    runs-on: ubuntu-latest

    # 작업 단계들
    steps:
      # 1. 소스 코드 체크아웃 (내 저장소의 코드를 가상 환경으로 가져옴)
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Dockerfile이 있는 경로 (backend 서비스 폴더 기준)
          context: .
          # Dockerfile 이름
          file: ./Dockerfile
          # 빌드 후 바로 푸시
          push: true

          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-image:latest
